/* Generated by RuntimeBrowser.
   Image: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/BulletinBoard.framework/BulletinBoard
 */

#import <Foundation/Foundation.h>

@interface BBSectionIcon : NSObject <NSCopying, NSSecureCoding> {
    NSSet *_variants;
}

@property(copy) NSSet * variants;

+ (BOOL)supportsSecureCoding;

- (id)_bestVariantForUIFormat:(int)arg1;
- (id)_bestVariantForFormat:(long long)arg1;
- (void)addVariant:(id)arg1;

@end