/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

@class NSString;

// struct __CTCall {};

@interface CTCall : NSObject {
    NSString *_callID;
    NSString *_callState;
}

@property(copy) NSString * callID;
@property(copy) NSString * callState;

+ (id)callForCTCallRef:(id)arg1;

- (void)dealloc;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;

@end
