/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

@class NSString;

@interface CTCarrier : NSObject {
    BOOL _allowsVOIP;
    NSString *_carrierName;
    NSString *_isoCountryCode;
    NSString *_mobileCountryCode;
    NSString *_mobileNetworkCode;
}

@property BOOL allowsVOIP;
@property(retain) NSString * carrierName;
@property(retain) NSString * isoCountryCode;
@property(retain) NSString * mobileCountryCode;
@property(retain) NSString * mobileNetworkCode;

- (void)dealloc;
- (id)description;
- (id)init;
- (BOOL)isEqual:(id)arg1;

@end
