/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

@class NSData, NSMutableDictionary, NSString;

@interface CTMessagePart : NSObject {
    NSString *_contentId;
    NSString *_contentLocation;
    NSString *_contentType;
    NSMutableDictionary *_contentTypeParams;
    NSData *_data;
}

@property(copy) NSString * contentId;
@property(copy) NSString * contentLocation;
@property(copy) NSString * contentType;
@property(copy) NSData * data;

- (void)addContentTypeParameterWithName:(id)arg1 value:(id)arg2;
- (id)allContentTypeParameterNames;
- (id)contentTypeParameterWithName:(id)arg1;
- (void)dealloc;
- (id)initWithData:(id)arg1 contentType:(id)arg2;
@end
