/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
 */

/* RuntimeBrowser encountered an ivar type encoding it does not handle. 
   See Warning(s) below.
 */

@class CTCarrier, NSDictionary, NSLock, NSString;

// struct dispatch_queue_s {};

struct queue { 
    dispatch_object_s *fObj; 
    NSString *_cachedCellId;
    NSString *_cachedCurrentRadioAccessTechnology;
    NSDictionary *_cachedSignalStrength;
    BOOL _monitoringCellId;
};

struct __CFRuntimeBase {
    unsigned int x_1_1_1;
    unsigned char x_1_1_2[4];
};

struct CTServerState {};
struct _xpc_connection_s {};

struct __CTServerConnection {
    __CFRuntimeBase x1;
    dispatch_queue_s *x2;
    CTServerState *x3;
    unsigned char x4;
    unsigned int x5;
    _xpc_connection_s *x6;
};

@interface CTTelephonyNetworkInfo : NSObject {
    queue _queue;
    CTCarrier *_subscriberCellularProvider;
    id _subscriberCellularProviderDidUpdateNotifier;
    struct __CTServerConnection *server_connection;
    NSLock *server_lock;
}

@property(retain) NSString * cachedCellId;
@property(retain) NSString * cachedCurrentRadioAccessTechnology;
@property(retain) NSDictionary * cachedSignalStrength;
@property(retain) NSString * cellId;
@property(readonly) NSString * currentRadioAccessTechnology;
@property(readwrite) BOOL monitoringCellId;
@property(retain) CTCarrier * subscriberCellularProvider;
@property(copy) id subscriberCellularProviderDidUpdateNotifier;

- (void)cleanUpServerConnection;
- (id)createSignalStrengthDictWithBars:(id)arg1;
- (void)dealloc;
- (BOOL)getAllowsVOIP:(BOOL*)arg1 withCTError:(coordinate*)arg2;
- (BOOL)getCarrierName:(id)arg1 withCTError:(coordinate*)arg2;
- (BOOL)getMobileCountryCode:(id)arg1 andIsoCountryCode:(id)arg2 withCTError:(coordinate*)arg3;
- (BOOL)getMobileNetworkCode:(id)arg1 withCTError:(coordinate*)arg2;
- (void)handleCTRegistrationCellChangedNotification:(id)arg1;
- (void)handleCTSignalStrengthNotification:(id)arg1;
- (void)handleNotificationFromConnection:(void*)arg1 ofType:(id)arg2 withInfo:(id)arg3;
- (id)init;
- (void)postCellularProviderUpdatesIfNecessary;
- (void)queryCTSignalStrengthNotification;
- (void)queryCellId;
- (void)queryDataMode;
- (id)radioAccessTechnology;
- (BOOL)setUpServerConnection;
- (id)signalStrength;
- (id)subscriberCellularProviderDidUpdateNotifier;
- (BOOL)updateNetworkInfoAndShouldNotifyClient:(BOOL*)arg1;
- (void)updateRadioAccessTechnology:(id)arg1;
- (void)updateSignalStrength:(id)arg1;

@end
