/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
 */

#import <UIKit/UIKit.h>
   
@interface SBFParallaxSettings { // _UISettings {
    NSInteger _distanceFromScreen;
    BOOL _increaseEnabled;
    NSInteger _slideDirectionX;
    NSInteger _slideDirectionY;
    BOOL _slideEnabled;
    CGFloat _slideIncreaseX;
    CGFloat _slideIncreaseY;
    CGFloat _slidePixelsX;
    CGFloat _slidePixelsY;
    CGFloat _tiltDegreesX;
    CGFloat _tiltDegreesY;
    NSInteger _tiltDirectionX;
    NSInteger _tiltDirectionY;
    BOOL _tiltEnabled;
}

@property NSInteger distanceFromScreen;
@property BOOL increaseEnabled;
@property NSInteger slideDirectionX;
@property NSInteger slideDirectionY;
@property BOOL slideEnabled;
@property CGFloat slideIncreaseX;
@property CGFloat slideIncreaseY;
@property CGFloat slidePixelsX;
@property CGFloat slidePixelsY;
@property CGFloat tiltDegreesX;
@property CGFloat tiltDegreesY;
@property NSInteger tiltDirectionX;
@property NSInteger tiltDirectionY;
@property BOOL tiltEnabled;

+ (id)settingsControllerModule;

- (NSInteger)distanceFromScreen;
- (BOOL)increaseEnabled;
- (void)setDefaultValues;
- (void)setDistanceFromScreen:(NSInteger)arg1;
- (void)setIncreaseEnabled:(BOOL)arg1;
- (void)setSlideDirectionX:(NSInteger)arg1;
- (void)setSlideDirectionY:(NSInteger)arg1;
- (void)setSlideEnabled:(BOOL)arg1;
- (void)setSlideIncreaseX:(CGFloat)arg1;
- (void)setSlideIncreaseY:(CGFloat)arg1;
- (void)setSlidePixelsX:(CGFloat)arg1;
- (void)setSlidePixelsY:(CGFloat)arg1;
- (void)setTiltDegreesX:(CGFloat)arg1;
- (void)setTiltDegreesY:(CGFloat)arg1;
- (void)setTiltDirectionX:(NSInteger)arg1;
- (void)setTiltDirectionY:(NSInteger)arg1;
- (void)setTiltEnabled:(BOOL)arg1;
- (NSInteger)slideDirectionX;
- (NSInteger)slideDirectionY;
- (BOOL)slideEnabled;
- (CGFloat)slideIncreaseX;
- (CGFloat)slideIncreaseY;
- (CGFloat)slidePixelsX;
- (CGFloat)slidePixelsY;
- (CGFloat)tiltDegreesX;
- (CGFloat)tiltDegreesY;
- (NSInteger)tiltDirectionX;
- (NSInteger)tiltDirectionY;
- (BOOL)tiltEnabled;

@end