/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoardFoundation.framework/SpringBoardFoundation
 */

#import "SBFParallaxSettings.h"

@interface SBFWallpaperParallaxSettings : SBFParallaxSettings {
    CGFloat _overhangX;
    CGFloat _overhangY;
    CGFloat _perspectiveTransform;
}

@property CGFloat overhangX;
@property CGFloat overhangY;
@property CGFloat perspectiveTransform;

+ (CGSize)_requiredOverhangSizeForCurrentDevice;
+ (CGSize)bestWallpaperSizeForParallaxFactor:(CGFloat)arg1;
+ (CGSize)minimumWallpaperSizeForCurrentDevice;
+ (CGSize)overhangSizeForCurrentDevice;
+ (id)settingsControllerModule;

- (CGFloat)overhangX;
- (CGFloat)overhangY;
- (CGFloat)perspectiveTransform;
- (void)setDefaultValues;
- (void)setOverhangX:(CGFloat)arg1;
- (void)setOverhangY:(CGFloat)arg1;
- (void)setPerspectiveTransform:(CGFloat)arg1;

@end